//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Downloader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Downloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed.
        /// </summary>
        public static string AppMissedHeader {
            get {
                return ResourceManager.GetString("AppMissedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed assotiated application..
        /// </summary>
        public static string AppMissedMessage {
            get {
                return ResourceManager.GetString("AppMissedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        public static string DownloadCompletedHeader {
            get {
                return ResourceManager.GetString("DownloadCompletedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileSuccessfully downloaded!.
        /// </summary>
        public static string DownloadCompletedMessage {
            get {
                return ResourceManager.GetString("DownloadCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DownloadingFailedHeader {
            get {
                return ResourceManager.GetString("DownloadingFailedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading failed.
        /// </summary>
        public static string DownloadingFailedMessage {
            get {
                return ResourceManager.GetString("DownloadingFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download from source Uri.
        /// </summary>
        public static string DownloadStartFailedMessage {
            get {
                return ResourceManager.GetString("DownloadStartFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exists..
        /// </summary>
        public static string FileMissedMessage {
            get {
                return ResourceManager.GetString("FileMissedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string FileRemovingHeader {
            get {
                return ResourceManager.GetString("FileRemovingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was successfully removed..
        /// </summary>
        public static string FileRemovingMessage {
            get {
                return ResourceManager.GetString("FileRemovingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Uri format!.
        /// </summary>
        public static string InvalidUriFormatMessage {
            get {
                return ResourceManager.GetString("InvalidUriFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string MainClear {
            get {
                return ResourceManager.GetString("MainClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string MainDownload {
            get {
                return ResourceManager.GetString("MainDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainSettings {
            get {
                return ResourceManager.GetString("MainSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloader.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string MenuContinue {
            get {
                return ResourceManager.GetString("MenuContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string MenuOpenFile {
            get {
                return ResourceManager.GetString("MenuOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        public static string MenuOpenFolder {
            get {
                return ResourceManager.GetString("MenuOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string MenuPause {
            get {
                return ResourceManager.GetString("MenuPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string MenuRemove {
            get {
                return ResourceManager.GetString("MenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveFile.
        /// </summary>
        public static string MenuRemoveFile {
            get {
                return ResourceManager.GetString("MenuRemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string SavedHeader {
            get {
                return ResourceManager.GetString("SavedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved.
        /// </summary>
        public static string SavedMessage {
            get {
                return ResourceManager.GetString("SavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string SettingsClose {
            get {
                return ResourceManager.GetString("SettingsClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy IP.
        /// </summary>
        public static string SettingsProxyIP {
            get {
                return ResourceManager.GetString("SettingsProxyIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy port.
        /// </summary>
        public static string SettingsProxyPort {
            get {
                return ResourceManager.GetString("SettingsProxyPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SettingsSave {
            get {
                return ResourceManager.GetString("SettingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving folder.
        /// </summary>
        public static string SettingsSavingFolder {
            get {
                return ResourceManager.GetString("SettingsSavingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string SettingsSelect {
            get {
                return ResourceManager.GetString("SettingsSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading threads.
        /// </summary>
        public static string SettingsThreads {
            get {
                return ResourceManager.GetString("SettingsThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use proxy.
        /// </summary>
        public static string SettingsUseProxy {
            get {
                return ResourceManager.GetString("SettingsUseProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download terminated.
        /// </summary>
        public static string TerminatedMessage {
            get {
                return ResourceManager.GetString("TerminatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateUri.
        /// </summary>
        public static string UpdateUriBtnText {
            get {
                return ResourceManager.GetString("UpdateUriBtnText", resourceCulture);
            }
        }
    }
}
